### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eiurur** [eiurur/ayase-heroku#2]
<s> - [ ] Gulp、Coffee、SASSに移行</s>
- [x] search機能の実装(/search/#{tag})
- [x] ng-infitie-scrollに移行
  - [x] 取得したデータは逐一Serviceで保持 
- [x] Shareボタン押して、出現したモーダルウィンドウの右上にある×ボタン押すとTOPに戻るの最悪だからShareボタンを消す、
- [x] ツイート数が50件を超えたらツイッターで告知してくれるbotとその処理を実装。

**Comment by eiurur** [comment]
Search機能はこれで賄えると思う → c086718eb90dff52be8e2abb1bb14336f60d0508

**Comment by eiurur** [comment]
![1424513182961](https://cloud.githubusercontent.com/assets/4101830/6769382/1eee2fbc-d0dc-11e4-9b21-993124b24805.jpg)
